[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "free_d6"
description = "The FREEd6 RPG System"
readme = "README.md"
authors = [{name = "Jeremy Deram"}]
urls = {homepage = "https://github.com/jderam/FREEd6"}
license = {file = "LICENSE"}
keywords = [
    "FREEd6",
    "RPG",
    "Dungeons",
    "Dragons",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dynamic = [
    "version",
]
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    # "build",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "ruff",
    # "twine",
    "uv-publish",
]

[tool.hatch.version]
path = "src/free_d6/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "src/free_d6",
    "LICENSE",
    "README.md",
]

[tool.hatch.build.targets.wheel]
packages = ["src/free_d6"]

[tool.ruff]
exclude = []
line-length = 100
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"src/free_d6/data.py" = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

[tool.pytest.ini_options]
addopts = "--cov=free_d6"
testpaths = ["tests"]
markers = [
    "repeat: repeats a test n times",
]
